site_name: ChatJulia 文档
site_url: https://ChatArch.github.io/ChatJulia
repo_url: https://github.com/ChatArch/ChatJulia
theme:
  name: material
  language: zh
nav:
  - 首页: index.md
  - English: index.en.md
